apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo-pod
  labels:
    app: nginx-demo
spec:
  containers:
  - name: nginx
    image: nginxdemos/hello
    # only information
    ports:
    - containerPort: 80
    volumeMounts:
    - name: demo-volume
      mountPath: /tmp/vols
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: demo-volume
    hostPath:
      path: /home/andy/playground/k8s/demo/01.pod/vols
      type: DirectoryOrCreate