@_default:
    just --list

install:
    mise use -g kind@0.29.0

create:
    kind create cluster --config ./kind-multi-node.yaml --name kind-multi-node

delete:
    kind delete cluster --name kind-multi-node

ls-kubectl-config:
    kubectl config current-context