@_default:
    just --list


create:
    kind create cluster --config ./kind-multi-node.yaml --name kind-multi-node

delete:
    kind delete cluster --name kind-multi-node

ls-kubectl-config:
    kubectl config current-context