@_default:
    just --list

generate-cert:
    mkdir -p certs
    openssl req -x509 -newkey rsa:4096 \
    -nodes -keyout certs/key.pem -out certs/cert.pem \
    -sha256 -days 3650 \
    -addext "subjectAltName = DNS:localhost"

# 25
[group("send-mail")]
send-no-auth-to-simple-server:
    #!/usr/bin/env bash
    set -euo pipefail
    nc -v localhost 25 < <(sleep 1;cat template/01.smtp-no-auth.txt | sed 's/$/\r/')

# 465
[group("send-mail")]
send-auth-plain-to-tls-server:
    #!/usr/bin/env bash
    set -euo pipefail
    openssl s_client -quiet -connect localhost:465 < <(sleep 1; cat template/03.smtp-auth-plain.txt | sed 's/$/\r/')
    # openssl s_client -quiet -connect localhost:465 -crlf < <(sleep 1; cat template/03.smtp-auth-plain.txt)
    # cat template/03.smtp-auth-plain.txt | openssl s_client -quiet -connect localhost:465 -crlf
    # cat template/03.smtp-auth-plain.txt | openssl s_client -connect localhost:465 -crlf

# 26 => 25
[group("send-mail")]
send-no-auth-and-relay-to-simple-server:
    #!/usr/bin/env bash
    set -euo pipefail
    nc -v localhost 26 < <(sleep 1;cat template/01.smtp-no-auth.txt | sed 's/$/\r/')

# 466 => 465
[group("send-mail")]
send-no-auth-and-relay-to-tls-server:
    #!/usr/bin/env bash
    set -euo pipefail
    nc -v localhost 466 < <(sleep 1;cat template/01.smtp-no-auth.txt | sed 's/$/\r/')

# 588 => 587
[group("send-mail")]
send-no-auth-and-relay-to-start-tls-server:
    #!/usr/bin/env bash
    set -euo pipefail
    nc -v localhost 588 < <(sleep 1;cat template/01.smtp-no-auth.txt | sed 's/$/\r/')

re-up:
    just down
    just up

up:
    docker compose up -d

down:
    docker compose down --remove-orphans

ps:
    docker compose ps