@_default:
    just  --list

@install:
    just install-kubectl
    just install-minikube

@run:
    minikube start

@install-kubectl:
    # ref: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
    # install
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

    # check
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
    echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check

    # set global
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    # clean
    rm kubectl kubectl.sha256

@install-minikube:
    # ref: https://minikube.sigs.k8s.io/docs/start/?arch=%2Flinux%2Fx86-64%2Fstable%2Fdebian+package
    # install
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
    sudo dpkg -i minikube_latest_amd64.deb

    # clean
    rm minikube_latest_amd64.deb