apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
    spec:
      containers:
      - name: pod
        image: nicolaka/netshoot:v0.13
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        command: [ "sleep", "3600" ]
        volumeMounts:
        - mountPath: /mnt/data
          name: pod
      volumes:
      - name: pod
        persistentVolumeClaim:
          claimName: my-pvc