services:
  node2:
    image: node:18
    volumes:
      - ./a:/app/a
      - public:/app/public
    entrypoint: sleep
    command: infinity
    environment:
      - aaaa=${TEST}
    networks:
      - main-net