@_default:
    just --list

get:
    kubectl get rs -o wide
    kubectl get pods -o wide
    kubectl get svc -o wide

create:
    kubectl apply -k .

delete:
    kubectl delete -k .

exec:
    kubectl exec -it netshoot -- bash

dump:
    kubectl exec -it netshoot -- host shop-service-cluster-ip
    kubectl exec -it netshoot -- host shop-service-headless