apiVersion: v1
kind: Pod
metadata:
  name: netshoot
spec:
  hostname: netshoot-hostname
  subdomain: netshoot-subdomain
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "infinity"]
