﻿apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /tmp/testing

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc-1
spec:
  containers:
    - name: app-1
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: data-volume
          readOnly: true
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: example-pvc

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc-2
spec:
  containers:
    - name: app-2
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: data-volume
          readOnly: true
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: example-pvc