apiVersion: v1
kind: Pod
metadata:
  name: nginx-by-yaml
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: alpine
    image: alpine
    command:
      - sleep
    args:
      - "3600"
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
  - name: net-shoot
    image: nicolaka/netshoot:v0.13
    command:
      - sleep
    args:
      - "3600"
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"